[input]
job_name = "medusa example"
directory = "input"
timeout = "48h"

[commands]
setup = '''
if ! command -v slither >/dev/null 2>&1; then
  echo "Installing solc and slither..."
  python3 -m venv ~/venv
  source ~/venv/bin/activate
  pip3 install solc-select slither-analyzer crytic-compile
  solc-select install 0.8.6
  solc-select use 0.8.6
fi

if ! command -v echidna >/dev/null 2>&1; then
  echo "Downloading echidna..."
  curl -fsSL -o /tmp/echidna.zip https://github.com/crytic/echidna/releases/download/v2.2.1/echidna-2.2.1-Linux.zip
  echo "Extracting echidna..."
  unzip /tmp/echidna.zip -d /tmp
  tar -xzf /tmp/echidna.tar.gz -C /tmp
  echo "Installing echidna..."
  mv /tmp/echidna /usr/local/bin
  rm /tmp/echidna.tar.gz
fi

if ! command -v medusa >/dev/null 2>&1; then
  echo "Downloading medusa..."
  sudo apt-get update; sudo apt-get install -y unzip
  curl -fsSL https://github.com/crytic/medusa/releases/download/v0.1.0/medusa-linux-x64.zip -o medusa.zip
  unzip medusa.zip
  chmod +x medusa
  sudo mv medusa /usr/local/bin
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "Installing docker and its dependencies..."
  apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  docker_key="$(curl -fsSL https://download.docker.com/linux/ubuntu/gpg)"
  echo "${docker_key}" | apt-key add -
  release="$(lsb_release -cs)"
  add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu ${release} stable"
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io
  user="$(whoami)"
  usermod -aG docker "${user}"
  systemctl enable docker
fi

if ! command -v forge >/dev/null 2>&1; then
  echo "Installing foundry..."
  curl -L https://foundry.paradigm.xyz | bash
  source /.bashrc
  foundryup
fi
'''

# This command is run after the setup script completes.
run = "medusa fuzz --target archive.zip"
