[input]
jobName = "medusa example"
directory = "input"
timeout = "48h"

[commands]
setup = '''
if ! command -v forge >/dev/null 2>&1; then
  echo "Installing foundry..."
  curl -L https://foundry.paradigm.xyz | bash
  source /.bashrc
  foundryup
fi
'''

# This command is run after the setup script completes.
run = "medusa fuzz"
