[input]
directory = "./input"
timeout = "48h"

[commands]
setup = '''
sudo apt-get update; sudo apt-get install -y unzip
curl -fsSL https://github.com/crytic/medusa/releases/download/v0.1.0/medusa-linux-x64.zip -o medusa.zip
unzip medusa.zip
chmod +x medusa
sudo mv medusa /usr/local/bin
'''

# This command is run after the setup script completes.
run = "cd ~/input && medusa fuzz --target archive.zip"
