name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Build with GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          # Skip the publishing step to test the binaries first
          args: release --skip-publish

      - name: Verify signatures
        run: |
          cd dist
          for file in *.{tar.gz,zip}; do
            if [ -f "$file" ]; then
              cosign verify-blob \
                --certificate-identity-regexp "https://github.com/crytic/cloudexec.*" \
                --certificate-oidc-issuer https://token.actions.githubusercontent.com \
                --bundle "$file.bundle" \
                $file
            fi
          done

      - name: Test built binary
        run: |
          ./dist/cloudexec_linux_amd64_v1/cloudexec version

      - name: Setup SSH Deploy Key
        uses: webfactory/ssh-agent@d4b9b8ff72958532804b70bbe600ad43b36d5f2e #v0.8.0
        with:
          ssh-private-key: ${{ secrets.HOMEBREW_TOOLS_DEPLOY_KEY }}

      - name: Publish release
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
